PYTHON BASICS

Split the Given String

In [1]:
s="Welcome to nalaiya thiran..!"
s.split(" ")

['Welcome', 'to', 'nalaiya', 'thiran..!']

Using .format()

In [2]:
fruit = "Mangoes."
eaten = 10
print("She has eaten {} big {}".format(eaten,fruit))

She has eaten 10 big Mangoes.


In this nest dictionary grab the word "hello"

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

NUMPY

In [4]:
import numpy as np

Create an array of 10 zeros?

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4.2 Create an array of 10 fives?

In [6]:
np.repeat(5, 10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Create an array of all the even integers from 20 to 35

In [7]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Concatinate a and b

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

PANDAS

Create a dataframe with 3 rows and 2 columns

In [11]:
import pandas as pd
pd.DataFrame(np.arange(6).reshape(3,2))

0  1
0  0  1
1  2  3
2  4  5

Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
pd.date_range(start="01-01-2023",end="10-02-2023")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

Create 2D list to DataFrame

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24